// Generates the `bunfig.toml` that wires the ttsc/Go lowering preload
// (scripts/ttsc-preload.ts) into every workspace package: in-repo resolution
// is source-first, so importing a lowering library throws on its first
// `typefor<T>()` call unless the transform is already installed as the module
// loader runs.
//
// bun discovers bunfig.toml by CWD alone -- there is no upward walk to a repo
// root -- and the suites run per package (`bun --filter '*' test`, `cd
// tests/x.test && bun test`), so the preload can only be wired in from a
// bunfig.toml living IN each package, never once at the repo root. `bun test`
// also reads its preload modules from `[test] preload`, never the top-level
// `preload` key `bun run` uses, so a bunfig serving both needs both.
//
// Every generated file carries the same three keys:
//   preload           <- `bun run` reads this
//   [install].linker  <- "isolated", mirroring the root bunfig.toml
//   [test].preload    <- `bun test` reads this instead of the top-level key
//
// Scope is every workspace package, read from the root package.json
// `workspaces` globs rather than hardcoded directory names.
//
// Modes:
//   --check   exit non-zero listing packages whose bunfig.toml is missing or
//             drifted from the derived content.
//   --write   (re)write bunfig.toml for every in-scope package.

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const PRELOAD_MODULE = join(ROOT, 'scripts', 'ttsc-preload.ts');
const HEADER = '# Generated by scripts/derive-preload-bunfig.ts --write -- do not hand-edit.\n';

interface RootManifest {
  readonly workspaces?: readonly string[];
}

/** The workspace group directories (e.g. "libraries", "tests") to generate into, read from the root package.json `workspaces` globs. */
function workspaceGroups(): string[] {
  const manifest = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as RootManifest;
  const groups = new Set<string>();
  for (const glob of manifest.workspaces ?? []) {
    const group = glob.split('/')[0];
    if (group) {
      groups.add(group);
    }
  }
  return [...groups].sort();
}

/** Every package directory (one per workspace member) under the in-scope groups. */
function discoverPackageDirs(): string[] {
  const dirs: string[] = [];
  for (const group of workspaceGroups()) {
    const groupDir = join(ROOT, group);
    let entries: string[];
    try {
      entries = readdirSync(groupDir);
    } catch {
      continue;
    }
    for (const entry of entries) {
      const pkgDir = join(groupDir, entry);
      if (existsSync(join(pkgDir, 'package.json'))) {
        dirs.push(pkgDir);
      }
    }
  }
  return dirs.sort();
}

/** The bunfig.toml content for `pkgDir`, pointing both preload keys at the shared module by its relative path from that package. */
function deriveBunfig(pkgDir: string): string {
  const rel = relative(pkgDir, PRELOAD_MODULE);
  const specifier = rel.startsWith('.') ? rel : `./${rel}`;
  return `${HEADER}preload = ["${specifier}"]\n\n[install]\nlinker = "isolated"\n\n[test]\npreload = ["${specifier}"]\n`;
}

function main(): void {
  const mode = process.argv[2];
  if (mode !== '--check' && mode !== '--write') {
    console.error('usage: derive-preload-bunfig.ts --check | --write');
    process.exit(2);
  }

  const drifted: string[] = [];
  const written: string[] = [];

  for (const pkgDir of discoverPackageDirs()) {
    const target = join(pkgDir, 'bunfig.toml');
    const derived = deriveBunfig(pkgDir);
    const current = existsSync(target) ? readFileSync(target, 'utf8') : undefined;
    if (current === derived) {
      continue;
    }
    drifted.push(relative(ROOT, pkgDir));
    if (mode === '--write') {
      writeFileSync(target, derived);
      written.push(relative(ROOT, pkgDir));
    }
  }

  if (mode === '--check') {
    if (drifted.length === 0) {
      console.log('Every workspace package bunfig.toml is in sync.');
      return;
    }
    console.error('bunfig.toml drift (run `bun scripts/derive-preload-bunfig.ts --write`):');
    for (const name of drifted) {
      console.error(`  - ${name}`);
    }
    process.exit(1);
  }

  if (written.length === 0) {
    console.log('No drift -- nothing rewritten.');
    return;
  }
  console.log(`Wrote bunfig.toml for ${written.length} package(s).`);
}

main();
