// The augmentation/DI key type — hoisted here from `di.core` (docs/decisions.md
// §38) so the augmentation registry (`augmentation-registry.ts`) can key its
// bags on it WITHOUT a di.core dependency: primitives is the zero-dep leaf every
// family already sees, and di ⊥ config forbids routing this through di.core.
//
// `di.core` now re-exports this type unchanged, so every consumer that imports
// `Token` from `@rhombus-std/di.core` keeps working.

/**
 * A stable string identifying an interface — the DI key AND the augmentation
 * registry key.
 *
 * No branding, no literal types. Generated by a transformer from a TypeScript
 * type at compile time (`nameof<T>()`); referenced by hand as a plain string
 * when using the manual authoring surfaces.
 */
export type Token = string;
