import type { Ctor, Func } from "@rhombus-toolkit/func";

/**
 * Anything a dependency signature can describe: a class constructor (its deps
 * are the ctor parameters) or a factory function (its deps are the call
 * parameters). The `never[]` rest keeps any concrete function assignable here
 * regardless of its own parameter list.
 */
export type DepTarget = Ctor | Func<never[], unknown>;

/**
 * A stable string identifying an interface — the DI key.
 *
 * No branding, no literal types. Generated by the transformer from a TypeScript
 * type at compile time; referenced by hand when using the manual authoring surfaces.
 */
export type Token = string;

/**
 * Marks a constructor parameter to be injected as a *factory* producing the
 * registered type token, rather than a resolved instance. The factory's own
 * call signature is determined by the caller-supplied `params` list.
 *
 * `type` is the token of the produced type T (replaces the former `.factory` field).
 * `params` is the complete, authored-order list of caller-supplied parameter tokens;
 * when present it pins the factory shape so it no longer drifts with registration state.
 */
export interface FactoryRef {
  readonly type: Token;
  readonly params?: readonly Token[];
}

/**
 * A set of alternative dependency slots tried in declaration order (first
 * resolvable member wins). If no member is resolvable, resolution throws.
 * Each member is itself a `DepSlot` — nesting is allowed.
 */
export interface Union {
  readonly union: readonly DepSlot[];
}

/**
 * A SINGULAR (non-union) type that supplies its value directly — no container
 * lookup. Emitted for:
 *   - a non-union literal param (`"dev"`, `42`, `true`, `1n`) → its value, and
 *   - a whole-type `void` / `undefined` → `undefined`; a whole-type `null` →
 *     `null` (a singleton type has exactly one inhabitant, so it is supplied
 *     directly, NOT tokenized — Rule 2).
 * The engine injects `value` verbatim. A LITERAL/typed UNION (`"a" | "b"`,
 * `Foo | undefined`) is NOT a `LiteralRef`: a literal union stays a resolved
 * token, and a nullish union is stripped by the optional/overload path. Always
 * satisfiable — the value is self-supplying.
 *
 * NOTE: `value` may legitimately be `undefined` (the `void`/`undefined` case),
 * so a `LiteralRef` is identified by the PRESENCE of the `value` key, never by
 * `value !== undefined`. See `isLiteralRef`.
 */
export interface LiteralRef {
  readonly value: string | number | boolean | bigint | undefined | null;
}

/**
 * Marks a parameter to be injected with the TOKEN STRING of one of the
 * registration's type arguments — the `typeof(T)` analog for open-generic
 * templates. `typeArg` is the 1-based hole number (`{ typeArg: 1 }` names the
 * argument bound to `$1`). At close time, substitution replaces the slot with
 * a `LiteralRef` carrying the substituted argument's token string; a raw
 * (unsubstituted) `TypeArgRef` reaching resolution is an error.
 */
export interface TypeArgRef {
  readonly typeArg: number;
}

/**
 * One positional slot in a constructor / factory signature:
 *   - a `Token` string  — a container-resolved dependency (a plain `Resolver`
 *     token resolves to the live provider view — see `RESOLVER_TOKEN`),
 *   - a `FactoryRef`    — a factory-injected parameter (see `FactoryRef`),
 *   - a `Union`         — member-level alternatives tried in order,
 *   - a `LiteralRef`    — a singular literal supplying its value directly, or
 *   - a `TypeArgRef`    — the token string of a type argument (see `TypeArgRef`).
 */
export type DepSlot = Token | FactoryRef | Union | LiteralRef | TypeArgRef;

/**
 * Per-constructor dependency metadata carried on a registration.
 *
 * `signatures` is an array of arrays: each element is one constructor signature
 * (for overload support). `signatures[i][j]` is the `DepSlot` — a token, a
 * `FactoryRef`, a `Union`, or a `LiteralRef` — for constructor parameter `j` of
 * overload `i`.
 */
export interface DepRecord {
  readonly signatures: readonly (readonly DepSlot[])[];
}

/**
 * The result of parsing a closed-generic token `base<arg1,arg2>` into its base
 * and top-level args. A pure data shape (the parse routine that produces it is a
 * runtime helper that lives in `@rhombus-std/di`); kept here so the type surface a
 * consumer references stays in the types-only substrate.
 */
export interface ParsedToken {
  readonly base: Token;
  readonly args: readonly Token[];
}

// ── Inject brand ──────────────────────────────────────────────────────────────

/**
 * Compile-time phantom brand that pins a specific token for one constructor or
 * factory parameter, overriding the token the transformer would normally derive.
 *
 * The value type stays `T` — a plain `T` is assignable because the brand
 * property is optional. Zero runtime footprint.
 *
 * @example
 * ```ts
 * class Handler {
 *   constructor(
 *     cache: Inject<ICache, "pkg:redis-cache">,  // pinned token
 *     log: ILogger,                              // derived normally
 *   ) {}
 * }
 * ```
 */
declare const TOK: unique symbol;
export type Inject<T, K extends Token> = T & { readonly [TOK]?: K };

// ── Hole brand (open generics) ────────────────────────────────────────────────

/**
 * Compile-time skolem standing in for the `N`th type argument of an open
 * template (1-based). Writing `add<IRepository<$<1>>>(SqlRepository<$<1>>)` binds
 * the hole; the transformer derives `$N` wherever a Hole-branded type appears.
 *
 * `C` is the constraint carrier: `Hole<1, Entity>` IS an `Entity` (the brand
 * property is optional, so the intersection stays assignable to `C`), which
 * lets a constrained implementation `class Repo<T extends Entity>` accept a
 * hole as its type argument. Zero runtime footprint.
 */
declare const HOLE: unique symbol;
export type Hole<N extends number, C = unknown> = C & { readonly [HOLE]?: N };

/**
 * Unbounded sugar for the common unconstrained hole: `$<1>`, `$<2>`, … `$<N>`.
 * `$<N>` is exactly `Hole<N>`; reach for `Hole<N, C>` when the impl's type
 * parameter carries a constraint the skolem must satisfy.
 */
export type $<N extends number> = Hole<N>;

// ── Typeof brand ────────────────────────────────────────────────────────

/**
 * Compile-time phantom brand marking a constructor parameter that receives the
 * TOKEN STRING of type argument `T` — the `typeof(T)` analog (hence the name).
 * The value type stays `Token` (a plain string is assignable; the brand
 * property is optional).
 *
 * `Typeof<T>` is type-driven: the transformer infers the hole from `T`. The
 * manual counterpart `typeArg(n)` is positional — a plugin-less author names
 * the hole by number.
 *
 * When `T` is a Hole, the transformer emits an open `{ typeArg: N }` slot that
 * substitution closes per registration; when `T` is concrete, it emits the
 * derived token directly as a literal value slot. Zero runtime footprint.
 *
 * @example
 * ```ts
 * class SqlRepository<T> {
 *   constructor(readonly entityToken: Typeof<T>) {}
 * }
 * ```
 */
declare const ARG: unique symbol;
export type Typeof<T> = Token & { readonly [ARG]?: T };

// ── Overload extraction ───────────────────────────────────────────────────────
//
// The builtin `Parameters<T>` / `ConstructorParameters<T>` see only the LAST
// overload of an overloaded function / constructor — every earlier signature is
// invisible. The utilities below recover the FULL set as a union of parameter
// tuples, which is how an overloaded ctor's shape survives into a factory: typing
// a factory rest parameter `(...args: OverloadedConstructorParameters<typeof C>)`
// makes the transformer emit one dep signature per constructor overload.

/**
 * ONE overload's own non-call properties, carried across the peeling recursion so
 * a callable-with-statics keeps them. `Pick<T, keyof T>` is `{}` for a bare
 * function type and the static side for a constructor type.
 */
type OverloadProps<T> = Pick<T, keyof T>;

/**
 * Peel an intersection of call signatures (an overloaded function type) into a
 * UNION of its individual signatures. The technique (Vojtěch Mašek / type-fest):
 * `infer` matches the LAST signature and emits it, then recurses with the
 * accumulator intersected back in so the next match resolves to the PRECEDING
 * overload. Bounded — each step strips one signature, terminating once the
 * accumulator already subsumes the whole overload set (`TAccumulator extends
 * TOverload`).
 */
type OverloadUnionRecursive<TOverload, TAccumulator = unknown> = TOverload extends
  (...args: infer TArgs) => infer TReturn ? TAccumulator extends TOverload ? never
  :
    | OverloadUnionRecursive<
      TAccumulator & TOverload,
      TAccumulator & ((...args: TArgs) => TReturn) & OverloadProps<TOverload>
    >
    | ((...args: TArgs) => TReturn)
  : never;

/**
 * The UNION of a function type's individual call-signature overloads. Seeds the
 * recursion with a `() => never` overload hoisted to the FRONT of the
 * intersection (required for the bounded recursion to fire), then excludes that
 * sentinel from the result unless `T` genuinely is `() => never`.
 */
type OverloadUnion<T extends (...args: any[]) => any> = Exclude<
  OverloadUnionRecursive<(() => never) & T>,
  T extends () => never ? never : () => never
>;

/**
 * Every overload's parameter tuple for a function type `T`, as a union — the
 * overload-faithful analog of the builtin `Parameters<T>`. For a `T` with
 * signatures `(a: A)` and `(a: B, b: C)` this is `[a: A] | [a: B, b: C]`; a
 * single-overload function yields its one tuple.
 */
export type OverloadedParameters<T extends (...args: any[]) => any> = Parameters<
  OverloadUnion<T>
>;

/** The construct-signature counterpart of {@link OverloadProps} — the static side. */
type ConstructorOverloadProps<T> = Pick<T, keyof T>;

/**
 * The construct-signature counterpart of {@link OverloadUnionRecursive}: peels an
 * intersection of CONSTRUCT signatures (an overloaded constructor type) into a
 * union of its individual signatures. A concrete `new` is used, NOT `abstract
 * new`: intersecting an abstract construct signature with a concrete class's
 * `new` signatures derails overload inference (it collapses to `any`), and the
 * sole consumer — a factory that does `new C(...args)` — needs a concrete
 * constructor anyway.
 */
type ConstructorOverloadUnionRecursive<TOverload, TAccumulator = unknown> = TOverload extends
  new(...args: infer TArgs) => infer TReturn ? TAccumulator extends TOverload ? never
  :
    | ConstructorOverloadUnionRecursive<
      TAccumulator & TOverload,
      TAccumulator & (new(...args: TArgs) => TReturn) & ConstructorOverloadProps<TOverload>
    >
    | (new(...args: TArgs) => TReturn)
  : never;

/** The construct-signature counterpart of {@link OverloadUnion}. */
type ConstructorOverloadUnion<T extends new(...args: any[]) => any> = Exclude<
  ConstructorOverloadUnionRecursive<(new() => never) & T>,
  T extends new() => never ? never : new() => never
>;

/**
 * Every construct-overload's parameter tuple for a constructor type `T`, as a
 * union — the overload-faithful analog of the builtin `ConstructorParameters<T>`.
 * For a `C` with constructors `(a: A)` and `(a: B, b: C)`,
 * `OverloadedConstructorParameters<typeof C>` is `[a: A] | [a: B, b: C]`; a
 * single-overload ctor yields its one tuple and a zero-arg ctor yields `[]`.
 * Constrained to a concrete (`new`-able) constructor — an abstract class has no
 * constructible instance, and the factory that consumes this must `new` its
 * argument.
 */
export type OverloadedConstructorParameters<
  T extends new(...args: any[]) => any,
> = ConstructorParameters<ConstructorOverloadUnion<T>>;
